name: Build site static dir with 'npm' and push to a dedicated 'Git' branch

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Update target branch by merging from master
      run: |        
        git config user.email auto@noreply.github.com
        git config user.name auto
        git checkout -B gh-pages
        git merge master

    - name: Build minimized and optimized production-ready site assets
      run: |
        npm install
        rm -rf docs
        npm run build-gh-pages
        
    - name: Push destination ("docs") dir 
      run: |      
        git add docs
        git commit -am "[auto] Build production dir"
        git push origin gh-pages
