name: Build site static dir with 'npm' and push to a dedicated 'Git' branch

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Recreate target branch
      run: |        
        git branch -D gh-pages 2>/dev/null
        git checkout -b gh-pages

    - name: Build minimized and optimized production-ready site assets
      run: |
        npm install
        npm run build-gh-pages
        
    - name: Push destination ("docs") dir 
      run: |        
        git config user.email auto@git-hub-actions.github.com
        git config user.name auto
        git commit --all -m "[auto] Build production dir"
        git push
